version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  proxy-nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # don't try to override the folder
      - ./server:/app # anytime the application tries to access anything inside the app directory inside the container
                      # except the node_module folder it is going to essentially get redirected back to the server directory inside our current project folder
    environment:
      - PGUSER=postgres
      - PGHOST=postgres # service name
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5342
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379